#!/bin/bash 

source ./functions/valid_ip

# Fill in your information from the machine you are running the script
# if its not localhost
local_address='localhost' 

srv_address=$1
remote_address=$2
ssh_port=$4
random_port="$((RANDOM % 900 + 8000))"



remote_port=$(echo "$remote_address" |cut -d ':' -f 2)
if ! echo "$2" |grep ':' &> /dev/null ; then
    remote_port='80'
else
    remote_port=$(echo "$remote_address" |cut -d ':' -f 2)
    secure='s'
fi

echo
printf "This tunel will be configured at http%s://%s:%s"  "$secure" "$remote_address" "$random_port"
echo 

remote_address=$(echo "$remote_address" |cut -d ':' -f 1)


    if [ "$3" == "-p" ]; then
        if valid_ip "$srv_address" ; then 
            ssh "$srv_address" -p "$ssh_port" -L "$local_address":"$random_port":"$remote_address":"$remote_port"
        else
            echo "Invalid ip address."
            exit 1
        fi
    else 
        if valid_ip "$CLIENTE" ; then 
            ssh "$srv_address" -p 22 -L "$local_address":"$random_port":"$remote_address":"$remote_port"
        else
            echo "Invalid ip address."
            exit 1
        fi
    fi


echo 
echo "Tunnel Closed"
exit 0

